Scene: default
Entities:
  - CameraComponent:
      camera:
        position: [2.24777246, 0.24708873, 0.567228198]
        yaw: 251.999466
        pitch: -19.1001301
        speed: 0.00100000005
        sensitivity: 0.300000012
        fov: 0.785398185
    BehaviourComponent:
      CameraBehaviour
  - AmbientLightComponent:
      color: [0.100000001, 0.100000001, 0.100000001]
  - DirectionalLightComponent:
      direction: [1, 1, 1]
      color: [1, 1, 1]
  - TransformComponent:
      position: [1.5, 0, 0]
      angle: 0
      rotation: [1, 1, 1]
      scale: [0.200000003, 0.200000003, 0.200000003]
    MeshComponent:
      {}
    MaterialComponent:
      shader: lit
      gloss: 6
      smoothness: 1
      metallicness: 0.2
  - TransformComponent:
      position: [2, 0, 0]
      angle: 0
      rotation: [0, 1, 0]
      scale: [0.100000001, 0.100000001, 0.100000001]
    ModelComponent:
      path: ../assets/backpack/backpack.obj
      flip_uvs: true
    MaterialComponent:
      shader: lit
      gloss: 6
      smoothness: 1
      metallicness: 0.1
  - BehaviourComponent:
      KeyboardBehaviour
  - BehaviourComponent:
      FPSCounterBehaviour
