Scene: default
Entities:
  - CameraComponent:
      camera:
        position: [0, 0, 10]
        yaw: -90
        pitch: 0
        speed: 0.000999999815
        sensitivity: 0.300000012
        fov: 0.785398185
    BehaviourComponent:
      CameraBehaviour
  - TransformComponent:
      position: [5, 10, 0]
      angle: 0
      rotation: [1, 1, 1]
      scale: [1, 1, 1]
    ModelComponent:
      path: ../assets/backpack/backpack.obj
      flip_uvs: true
  - TransformComponent:
      position: [1.5, 1.5, 0]
      angle: 1.57079995
      rotation: [0, 0, 1]
      scale: [1, 1, 1]
    MeshComponent:
      color: [1, 0, 0]
    BehaviourComponent:
      RotationBehaviour
  - TransformComponent:
      position: [0, 0, 0]
      angle: 1.57079995
      rotation: [0, 0, 1]
      scale: [1, 1, 1]
    MeshComponent:
      color: [0, 1, 0]
    BehaviourComponent:
      ArrowsControlBehaviour
  - TransformComponent:
      position: [2.5, 0, 0]
      angle: 1.57079995
      rotation: [0, 0, 1]
      scale: [1, 1, 1]
    MeshComponent:
      color: [0, 0, 1]
    BehaviourComponent:
      KeyboardBehaviour
  - TransformComponent:
      position: [0, -10, 0]
      angle: 1.57079995
      rotation: [1, 0, 0]
      scale: [100, 100, 100]
    MeshComponent:
      {}
    BodyComponent:
      type: Static
      linear_velocity: [0, 0, 0]
      angular_velocity: 0
      has_fixed_rotation: false
      gravity_scale: 1
      fixtures:
        - shape:
            type: Quad
            width: 1
            height: 1
          local_position: [0, 0, 0]
          friction: 0.200000003
          restitution: 0
          density: 1
