Scene: default
Entities:
  - CameraComponent:
      camera:
        position: [1.47554326, 0.231499761, 1.14498329]
        yaw: 273.29953
        pitch: -8.60012722
        speed: 0.00100000005
        sensitivity: 0.300000012
        fov: 0.785398185
    BehaviourComponent:
      CameraBehaviour
  - AmbientLightComponent:
      color: [0.100000001, 0.100000001, 0.100000001]
  - DirectionalLightComponent:
      direction: [1, 1, 1]
      color: [1, 1, 1]
  - TransformComponent:
      position: [1.5, 0, 0]
      angle: 0
      rotation: [1, 1, 1]
      scale: [0.00999999978, 0.00999999978, 0.00999999978]
    MeshComponent:
      type: Sphere
      radius: 10
      x_segment: 20
      y_segment: 20
    MaterialComponent:
      shader: lit
      gloss: 6
      smoothness: 1
      metallicness: 0.200000003
      color: [1, 0, 0]
  - TransformComponent:
      position: [1, 0, 0]
      angle: 0
      rotation: [1, 1, 1]
      scale: [0.00999999978, 0.00999999978, 0.00999999978]
    MeshComponent:
      type: Sphere
      radius: 10
      x_segment: 20
      y_segment: 20
    MaterialComponent:
      shader: lit
      gloss: 6
      smoothness: 1
      metallicness: 0.200000003
      color: [1, 0, 1]
      topology: 4
  # - TransformComponent:
  #     position: [2, 0, 0]
  #     angle: 0
  #     rotation: [0, 1, 0]
  #     scale: [0.100000001, 0.100000001, 0.100000001]
  #   MaterialComponent:
  #     shader: lit
  #     gloss: 6
  #     smoothness: 1
  #     metallicness: 0.100000001
  #     color: [1, 1, 1]
  #     topology: 4
  #   ModelComponent:
  #     path: ../assets/backpack/backpack.obj
  #     flip_uvs: true
  # - BehaviourComponent:
  #     KeyboardBehaviour
  # - BehaviourComponent:
  #     FPSCounterBehaviour
